import "./globals.css";
import { Manrope, Montserrat } from "next/font/google"
import Header from "./components/Header";


const manrope = Manrope({
  subsets: ['latin'],
  display: 'swap',
})

const montserrat = Montserrat({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-montserrat'
})


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${manrope.className} ${montserrat.variable}`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
